### ISSUE TITLE
hardened description typo

### ISSUE THREAD

**Issue by VaporeonScripts** [Explorers-Eden/Enchantments-Encore#14]
armmor

**Comment by VaporeonScripts** [comment]
1.21.1 neoforge

**Comment by NiceKaleido** [comment]
Thanks for letting me know. Is fixed in the soon to be released 1.21.4 release :)

**Comment by VaporeonScripts** [comment]
btw, another typo:
![image](https://github.com/user-attachments/assets/131e1e4b-b9a8-4186-bd97-45bb80912117)
(not capitalized)
