### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kevATin** [Explorers-Eden/Enchantments-Encore#2]
Hey, nice datapack! Are you open to suggestions for enchantments?

Things i'd like to see would be:

- walking on powdered snow (without leather boots)
- soul bound, the item stays in your inventory through death, each time it's used it decreases by 1 level, at level 0 it vanishes, could go up to level 10, and ideally you could also apply it to items like shulker boxes, bundles, written books, maps, etc
- mining spawners (not silk touch?)
- turtle shell properties on a helmet
- pumpkin enderman protection on a helmet
- gold-like piglin protection on non-gold items
- an enchantment that makes the tool able to mine blocks of higher tiers, eg if you put it onto a gold pickaxe you can mine obsidian with it,
- make the unbreaking enchantment go to much higher levels, so gold tools can become more viable

**Comment by NiceKaleido** [comment]
Thanks for the suggestions. Most of your ideas are great but are also not that easy possible on first thought. I look into it a bit further. :)
