### ISSUE TITLE
[Bug] Forge Shot enchantment causes game crash and corrupts save file

### ISSUE THREAD

**Issue by kunieone** [Explorers-Eden/Enchantments-Encore#9]
Description
When using a bow with Forge Shot enchantment bow to damage a mob, the game crashes and the save file becomes unloadable afterwards.
Steps to Reproduce

Obtain a bow with Forge Shot enchantment
Hit a mob with it
Game crashes
Save file can't be opened anymore

This issue can be consistently reproduced on different computers.
The crash only occurs when actually hitting a mob, not when missing.

Please try to fix it! Thank you. I Can't open my archive right now.

some logs:

[19:47:08] [dimthread_server_overworld/ERROR] [ne.ne.bu.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.world.entity.item.FallingBlockEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (net.minecraft.world.entity.item.FallingBlockEntity and net.minecraft.world.entity.LivingEntity are in module minecraft@1.21 of loader 'TRANSFORMER' @72168258)
	Index: 0
	Listeners:
		0: @SubscribeEvent: class neoforge.com.cursee.new_shield_variants.event.NSVEnderShieldBlockEvent shieldBlockEvent(Lnet/neoforged/neoforge/event/entity/living/LivingShieldBlockEvent;)V
		1: @SubscribeEvent: class baguchan.tofucraft.CommonEvents onShieldEvent(Lnet/neoforged/neoforge/event/entity/living/LivingShieldBlockEvent;)V
java.lang.ClassCastException: class net.minecraft.world.entity.item.FallingBlockEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (net.minecraft.world.entity.item.FallingBlockEntity and net.minecraft.world.entity.LivingEntity are in module minecraft@1.21 of loader 'TRANSFORMER' @72168258)

**Comment by kunieone** [comment]
![image](https://github.com/user-attachments/assets/bd76cc67-0812-497a-9c1b-c2df091ae780)

It looks like this thing caused the crash

**Comment by NiceKaleido** [comment]
can't be reproduced on a vanilla client. If this problem persists, try open an issue with neoforge.
